/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings src/generated-bindings.d.ts` (hash: 5a9cc31552536e0ec9f71184c05f5551)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	PUBLIC_ORIGIN: "https://api.clovapi.com";
	ALLOWED_ORIGINS: "https://clovapi.com,https://www.clovapi.com";
	COOKIE_SECURE: "true";
	AUTH_SECRET: string;
	RESEND_API_KEY: string;
	RESEND_FROM: string;
	NODE_SESSIONS: DurableObjectNamespace<import("./index").NodeSession>;
	ACCOUNT_GATES: DurableObjectNamespace<import("./index").AccountGate>;
	AUTH_RATE_GATES: DurableObjectNamespace<import("./index").AuthRateGate>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "NodeSession" | "AccountGate" | "AuthRateGate";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "ALLOWED_ORIGINS" | "COOKIE_SECURE" | "AUTH_SECRET" | "RESEND_API_KEY" | "RESEND_FROM">> {}
}
