import { FIXED_PROVIDER_IDS } from "../constants";
import type { ModelAdapterDef, ModelListItem, ModelTestEntry, ProxyLogEntry, ProxySystemLogEntry, ProviderDef, SubscriptionItem, Vendor } from "../../global";

export type TabId = "profiles" | "models" | "call-logs" | "system-logs" | "settings";

export const store = $state({
  activeTab: "models" as TabId,
  profiles: [] as Vendor[],
  profilesPath: "",
  running: false,
  ollamaInstalled: false,
  clovapiAvailable: false,
  editingProfileName: "",
  subscriptions: [] as SubscriptionItem[],
  subscriptionLogging: {} as Record<string, boolean>,
  modelTests: {} as Record<string, ModelTestEntry>,
  profileDialogOpen: false,
  profileDialogMode: "create" as "create" | "edit",
  modelDialogOpen: false,
  modelDialogMode: "create" as "create" | "edit",
  modelDialogVendorName: "",
  editingModelId: "",
  formName: "",
  formBaseUrl: "",
  formApiKey: "",
  formModelAdapter: "openai-compatible" as import("../../global").ModelAdapterId,
  formNameDisabled: false,
  formModelLabel: "",
  formModelName: "",
  formModelBaseUrl: "",
  formModelApiKey: "",
  formModelApiStyle: "openai-responses",
  proxyRunning: false,
  proxyHost: "0.0.0.0",
  proxyPort: 27483,
  proxyBaseUrl: "http://127.0.0.1:27483",
  proxyAddressDraft: "http://127.0.0.1:27483",
  proxyHealthTest: null as import("../../global").ModelTestEntry | null,
  appVersion: "",
  appUpdateAvailable: false,
  appLatestVersion: "",
  appUpdateCheck: null as import("../../global").ModelTestEntry | null,
  appUpdating: false,
  appUpdateProgress: 0,
  appUpdateProgressReceivedBytes: 0,
  appUpdateProgressTotalBytes: 0,
  coreVersion: "",
  coreLatestVersion: "",
  coreUpdateAvailable: false,
  coreUpdating: false,
  coreUpdateCheck: null as import("../../global").ModelTestEntry | null,
  proxyLogs: [] as ProxyLogEntry[],
  proxySystemLogs: [] as ProxySystemLogEntry[],
  proxyLogsLoading: false,
  proxyLogsPageSize: 20,
  proxyLogsOffset: 0,
  proxyLogsHasMore: false,
  proxyLogSelectedId: null as string | null,
  proxySystemLogSelectedId: null as string | null,
  vendorFetching: {} as Record<string, boolean>,
  vendorUsage: {} as Record<string, { summary: string; rows: import("../../global").VendorUsageData[]; error: string }>,
  vendorUsageLoading: {} as Record<string, boolean>,
  profilesSelectedVendor: null as string | null,
  modelAdapters: [] as ModelAdapterDef[],
  providers: [] as ProviderDef[],
  fixedProviderIds: [...FIXED_PROVIDER_IDS] as string[],
  modelList: [] as ModelListItem[],
  modelListLoading: false,
});
